config/routes.rb
Rails.application.routes.draw do
  root   'sessions#new'
 
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
  resources :users  do
    member do
      get 'user_home'
      get 'admin_home'
    end 
    resources :articles do
      collection do
        get 'user_articles'
      end
      member do
        post 'request_status'
        post 'approved_article'
        post 'deny_article'
        get 'show_approved_articles'
        get 'like'
       
      end 
      resources :comments do
        resources :replies
      end   
    end

  end

  namespace :articles do
    get 'list_of_requested_articles'
    get 'list_of_approved_articles'
  end



end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  has_many :replys ,dependent: :destroy
  validates :body, presence: true
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, :default_url => "/system/avatars/:style/missing.png"
	validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif","application/pdf", "application/xlsx"], :message => ", Only PDF And Image files are allowed. "
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create

    @user = User.find(params[:user_id])
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user_id=@current_user.id

    if @current_user.present?
      if @comment.save
        respond_to do |format|
          format.html { redirect_to show_approved_articles_user_article_path(@user,@article) }
          format.js 
        end
        CommentMailer.comment_email(@user,@article,@comment).deliver
      else
        flash[:error] = "please enter Comment"  
      end
    
    else
      flash[:notice] = "Please Login"
      redirect_to root_url
    end  
  end


  def destroy
    
    @user = User.find(params[:user_id])
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    if @comment.destroy
      flash[:notice] = "destory Sucessfully!"
      redirect_to show_approved_articles_user_article_path(@user,@article) 
    end
  end


  def show
    @user = User.find(params[:user_id])
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    
  end



  private
  def comment_params
    params.require(:comment).permit(:body,:avatar)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
	
end

app/views/comments/_comment.html.erb
<% comments.each do |comment| %>
  <p>
    <strong style="color:#008080;">Commenter:</strong>
    <%@cname=User.find(comment.user_id)%>
    <%=@cname.name + " " + @cname.surname%>
  </p>
  <p>
    <strong style="color:#008080;">Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
    <%if comment.avatar.present? %>
      <strong>File:</strong>
      <%= link_to image_tag(comment.avatar.url(:med)), comment.avatar.url %>
    <%end%>
    <%@comment=comment%>

    <%if comment.present?%>

      <%= button_to 'reply', user_article_comment_path(@user, @article, @comment),method: :get, class:"btn btn-info btn-xs"%>

    <%end%>
  </p>

  <p>
    <%if @current_user.id == comment.user_id%>

      <%= link_to 'Destroy Comment',  user_article_comment_path(@user, @article, comment) ,method: :delete,data: { confirm: 'Are you sure?' } %>
    <%end%>

  </p>
<%end%>

app/views/comments/_form.html.erb
<p><%= flash[:error] unless flash[:error].blank? %></p>
<%= form_for([@user,@article, @article.comments.build],:remote => true,html: { multipart: true }) do |f| %>
  <div class="form-group">
    <div class="col-md-3">
      <%= f.text_area :body ,class:"form-control"%>
    </div>  
  </div>
  <br>
  <br>
  <br>
    <div class="col-md-3">
  	  <b style="color:#ff3300;">only pdf and Images are allowed.</b>
    </div>
  <br>
  <br>
   
  <div class="form-group">
    <div class="col-md-3">
  	  <%= f.file_field :avatar,class:".form-control-file" %>
    </div>
  </div>
  <br>
  
  
  
  <div class="form-group">
    <%= f.submit "create comment",class:"btn btn-default col-md-2"%>
   
  </div>
<% end %>

app/views/comments/create.js.erb
$('#com').html("<%= j render(:partial => 'comments/comment', :locals => { comments: @article.comments }) %>");

app/views/comments/show.html.erb
<%= link_to 'Back', show_approved_articles_user_article_path(@user,@article)%>
<p>
  <strong>Commenter:</strong>
    <%@cname=User.find(@comment.user_id)%>
    <%=@cname.name + " " + @cname.surname%>
</p>
<p>
  <strong>Comment:</strong>
  <%= @comment.body %>
</p>

<div id='repshow'>
	<h2><strong style="color: #008066;">Rplies</strong></h2>
  <%= render 'replies/reply', replies: @comment.replys %>
</div>


<h2>Create Reply:</h2>
<%= render 'replies/form' %>