config/routes.rb
Rails.application.routes.draw do
  root   'sessions#new'
 
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
  resources :users  do
    member do
      get 'user_home'
      get 'admin_home'
    end 
    resources :articles do
      collection do
        get 'user_articles'
      end
      member do
        post 'request_status'
        post 'approved_article'
        post 'deny_article'
        get 'show_approved_articles'
        get 'like'
       
      end 
      resources :comments do
        resources :replies
      end   
    end

  end

  namespace :articles do
    get 'list_of_requested_articles'
    get 'list_of_approved_articles'
  end



end

app/models/article.rb
class Article < ApplicationRecord
  enum status: { request_not_send: 0,request_send: 1 ,request_approved: 2 ,request_denied:3}
  belongs_to :user 
  has_many :comments ,dependent: :destroy
  has_many :likes
  validates :title, presence: true,length: { minimum: 5 }, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
  validates :text, presence: true,length: { minimum: 5 }
 
                 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @user = User.find(params[:user_id])
    @article = Article.find(params[:id])
  end
 
  def new
    @user = User.find(params[:user_id])
    @article = Article.new
  end
 
  def create
    @user = User.find(params[:user_id])
    @article = @user.articles.new(article_params)
    
    if @current_user.present?
      if @article.save
        if @user[:role]=="admin"
          redirect_to admin_home_user_path(@user)
        else
          redirect_to user_home_user_path(@user)
        end
        ArticleMailer.article_status(@user,@article).deliver
      else
        flash[:error] = "please enter Title and Text Both."
        render 'new'
      end
    else
      flash[:error] = "please login."
      redirect_to  root_url
    end    
  end

  def list_of_requested_articles
    @articles=Article.where(:status => 'request_send')
  end

  def list_of_approved_articles
     @articles=Article.where(:status => 'request_approved')
  end
 

  def user_articles
    @user = User.find(params[:user_id])
    @articles = @user.articles
  end
  

  def request_status
    @user = User.find(params[:user_id])
    @article = Article.find(params[:id])
    @article.update_column(:status,"1")
    respond_to do |format|
      format.js { render :layout=>false}
    end 
    UserMailer.request_email(@user,@article).deliver
  end

  def approved_article
    @user = User.find(params[:user_id])
    @article = Article.find(params[:id])
    @article.update_column(:status,"2")
    respond_to do |format|
      format.js { render :layout=>false}
    end
    
    UserMailer.notification_eamil(@user,@article).deliver

  end
  
  def deny_article
    @user = User.find(params[:user_id])
    @article = Article.find(params[:id])
    @article.update_column(:status,"3")
    respond_to do |format|
      format.js { render :layout=>false}
    end

    UserMailer.notification_eamil(@user,@article).deliver
  end


  def destroy
    @user = User.find(params[:user_id])
    @article = Article.find(params[:id])
    if @current_user.present?
      @article.destroy
      respond_to do |f|
        f.html { redirect_to user_articles_user_articles_path(@user) }
        f.js
      end
    else
      flash[:error] = "please Login."
      redirect_to root_url
    end  
  end

  def show_approved_articles
    @user = User.find(params[:user_id])
    @article = Article.find(params[:id])
  end


  def edit
    @user = User.find(params[:user_id])
    @article = Article.find(params[:id])  
  end


  def update
    @user = User.find(params[:user_id])
    @article = Article.find(params[:id])
    
    if @article.update(article_params)
      redirect_to user_articles_user_articles_path(@user)
    else
      render 'edit'
      flash.now[:error] = "Could not save client"
    end
  end
  
  def like
    @article = Article.find(params[:id])
    @like = @article.likes.new
    @like.user_id=@current_user.id
    if @like.save
      respond_to do |format|
        format.html { redirect_to articles_list_of_approved_articles_path() }
        format.js 
      end
    end  
    
  end

  

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/ deny_article.js.erb
 $('.status_for_deny')[0].value = "Denied"

app/views/articles/_form.html.erb
<%= form_for [@user,@article] do |f| %>

<%if @article.errors.any? %>

    <div id="error_explanation">
      <h2 style="color:#ff3300;">
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>


  <div class="form-group">
    <div class="col-md-3">
      <%= f.label :title %><br>
      <%= f.text_field :title,class:"form-control" %>
    </div>
  </div>

<br>
<br>
<br>
<br>
 

  <div class="form-group">
    <div class="col-md-3">
      <%= f.label :text %><br>
      <%= f.text_area :text,class:"form-control" %>
    </div>
  </div>

<br>
<br>
<br>
<br>
<br>


 
  <div class="form-group">
    <%= f.submit "Create Article",class:"btn btn-info btn-md col-md-2"%>
  </div>

 
<% end %>

app/views/articles/approved_article.js.erb
$('.status_for_approve')[0].value = "Approved"

app/views/articles/deny_article.js.erb
 $('.status_for_deny')[0].value = "Denied"

app/views/articles/destroy.js.erb
$('#row_<%= @article.id %>').remove();

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back',user_articles_user_articles_path(@user) %>

app/views/articles/like.js.erb
// $('#likecount')[0].value = "Unlike"
$("#likecount").attr("disabled", true);

app/views/articles/list_of_approved_articles.html.erb
<h1>Listing of Approved articles</h1>

<table class="table table-striped">
  <tr style="color:#3399ff;" >
    <th > User Name</th>
    <th>Article Title</th>
    <th>Date of Article Creation</th>
  </tr>

  <% @articles.each do |article| %>
  <tr>
    <%@user_name = User.find(article.user_id)%>
    <td><%= @user_name.name + " " + @user_name.surname %></td>
    <td><%= article.title %></td>
    <td> <%=article.created_at.strftime("%d %B, %Y") %></td>
    <td> <%= link_to 'View',show_approved_articles_user_article_path(@user_name.id, article.id) %>
    </td>
    <td>

      <% @like=Like.where(:user_id => @current_user.id,:article_id =>article.id)%>  
      <%if !@like.present?%>
        <span class="glyphicon glyphicon-thumbs-up"%></span><%= article.likes.count%> <%=button_to 'Like',like_user_article_path(@user_name.id,article.id),method: :get,:remote => true, id: 'likecount',class:"btn btn-default btn-sm" %> 

      <%else%>

        <span class="glyphicon glyphicon-thumbs-up"%></span><%= article.likes.count%><%=button_to 'Liked',like_user_article_path(@user_name.id,article.id),method: :get,disabled: true,class:"btn btn-default btn-sm" %> 
        
      <%end%>
    </td> 
  </tr>
  <%end%>

</table>

<%= link_to 'Back', user_home_user_path(@current_user)  %>

app/views/articles/list_of_requested_articles.html.erb
<h1>Listing of Requested articles</h1>

<table class="table table-striped">
  <tr  style="color:#3399ff;" >
    <th>User Name</th><td> </td>
    <th >Article Title</th>
    <th>Date of  Article Creation</th>
   
  </tr>
  <% @articles.each do |article| %>
  <tr>
    <%@user_name = User.find(article.user_id)%>
    <td ><%= @user_name.name + " " + @user_name.surname %></td><td></td>
    <td ><%= article.title %></td>
    <td> <%=article.created_at.strftime("%d %b, %Y") %></td>
    <td><%= link_to 'Show',user_article_path(@user_name.id, article.id) %></td>
    <td>
      <%if @current_user.admin? && article.request_send?%>
        <div class="btn-group">
        <%= button_to "Approve",approved_article_user_article_path(@user_name,article.id),:remote => true, class:'status_for_approve btn btn-success'%>
        <% if  article.request_send? && !article.request_approved?%>
        <%= button_to "Deny",deny_article_user_article_path(@user_name,article.id),:remote => true, class:'status_for_deny btn btn-danger'%>
        <%end%>
      </div>
      <%end%>
    </td>
  </tr>
  <%end%>
</table>
<%= link_to 'Back',admin_home_user_path(@current_user) %>

app/views/articles/new.html.erb
<p><%= flash[:error] unless flash[:error].blank? %></p>
<h1  style="color:#3399ff;" >New article</h1>
 
<%= render 'form' %>
<br>
<br>
<%if @user.user? %>
  <%= link_to 'Back', user_home_user_path(params[:user_id]) %>
<%else%>
  <%= link_to 'Back',admin_home_user_path(params[:user_id])%>
<%end%>

app/views/articles/request_status.js.erb
$('.status')[0].value = "request sent"

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>


<%if @user.user? && @article.request_not_send?%>
  <%= button_to "Request for approve", request_status_user_article_path(params[:user_id],params[:id]),:remote => true, class:'status btn btn-info' %>

<%else %>
  <%if @current_user.user? %>
    <%= button_to "Request send",request_status_user_article_path(params[:user_id],params[:id]),disabled: true,class:"btn btn-warning" %>
  <%end%>
     
  <%if @current_user.admin? && @article.request_send?%>
    <div class="btn-group">
    <%= button_to "Approve",approved_article_user_article_path(params[:user_id],params[:id]),:remote => true, class:'status_for_approve btn btn-success'%>
    <br>

    <%= button_to "Deny",deny_article_user_article_path(params[:user_id],params[:id]),:remote => true, class:'status_for_deny btn btn-danger'%>
    </div>
  <%end%>

<%end%>

<br>
<br>


<%if @current_user.admin? && @article.request_send?%>
  <%= link_to 'Back',articles_list_of_requested_articles_path() %>
<%else%>
  <%= link_to 'Back', user_articles_user_articles_path(params[:user_id]) %>
<%end%>

app/views/articles/show_approved_articles.html.erb
<p><%= flash[:notice]  %></p>
<%= link_to 'Back',articles_list_of_approved_articles_path()%>
<p>

  <strong style="color:#ff6666;">Title:</strong>
  <%= @article.title %>
</p>
<p>
  <strong style="color:#ff6666;">Text:</strong>
  <%= @article.text %>
</p>

<h2 style="color: #000066;">Comments</h2>
<div id='com'>
  <%= render 'comments/comment', comments: @article.comments %>
</div>


<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/articles/user_articles.html.erb
<h1>Listing articles</h1>

<table class="table" "table-hover" >
  <tr  style="color:#3399ff;" >
    <th >Title</th>
    <th>date of Article Created</th>
    <th>Date of Update Article</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th>Status</th>
  </tr>
 
  <% @articles.each do |article| %>

    <tr id="row_<%= article.id%>">
      <td><%= article.title %></td>
      <td> <%=article.created_at.strftime("%d %B, %Y") %></td>
      <td> <%=article.updated_at.strftime("%d %B, %Y") %></td>
     
      <td><%= link_to 'Show',user_article_path(@user.id, article.id) %></td>
      <td><%= link_to 'Destroy',user_article_path(@user.id, article.id),
              method: :delete,
              data: { confirm: 'Are you sure?' },:remote => true%></td>
      
      <td><%= link_to 'Edit',edit_user_article_path(@user.id, article.id) %></td>
      <td>

        <%if @user.user? && article.request_not_send?%>
          <%= button_to "Request for approve", request_status_user_article_path(params[:user_id],article.id),:remote => true, class:'status btn btn-info' %>

        <%else %>
          <%if @current_user.user? %>
            
            <%= button_to "Request send",request_status_user_article_path(params[:user_id],article.id),disabled: true ,class:"btn btn-warning"%>
          <%end%>
        <%end%>
      </td>  
      <td>
        <%= article.status%>
      </td>  
    </tr>
  <% end %>
</table>

<%if @user.user?%>
  <%= link_to 'Back',user_home_user_path(params[:user_id])%>
<%else%>
  <%= link_to 'Back',admin_home_user_path(params[:user_id])%>
<%end %>