config/routes.rb
Rails.application.routes.draw do
  root   'sessions#new'
 
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
  resources :users  do
    member do
      get 'user_home'
      get 'admin_home'
    end 
    resources :articles do
      collection do
        get 'user_articles'
      end
      member do
        post 'request_status'
        post 'approved_article'
        post 'deny_article'
        get 'show_approved_articles'
        get 'like'
       
      end 
      resources :comments do
        resources :replies
      end   
    end

  end

  namespace :articles do
    get 'list_of_requested_articles'
    get 'list_of_approved_articles'
  end



end

app/models/user.rb
class User < ApplicationRecord

  enum role: { user: 0, admin: 1 }
  has_many :articles ,dependent: :destroy
  has_many :likes
  validates :name, presence: true,length: { minimum: 5 },format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
  validates :surname, presence: true,length: { minimum: 5 },format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
  validates :email, presence: true
  validates :mobile, presence: true,length: { minimum: 10 }
  validates :password, presence: true,length: { minimum: 4 }
  validates :password_confirmation, presence: true,length: { minimum: 5 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      respond_to do |f|
        f.html { redirect_to login_path }
       
      end
    end
    UserMailer.welcome_email(@user).deliver
  end

  def show
    @user = User.find(params[:id])
  end
  
  
  def user_home   
  end

  def admin_home
  end  

  private
  def user_params
    params.require(:user).permit(:name, :surname, :email,:mobile,:password,
                                   :password_confirmation)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/admin_home.html.erb
<div class="row"> 

	<%= button_to "Create New Article", new_user_article_path(params[:id]),method: :get,class:"btn btn-info col-md-4" %>
		
	<%= button_to "View My Articles" , user_articles_user_articles_path(params[:id]),method: :get,class:"btn btn-success col-md-4"%>
		
	<%= button_to " List of Request Articles",articles_list_of_requested_articles_path(),method: :get,class:"btn btn-warning col-md-4"%>
		
</div>

app/views/users/new.html.erb
<%= form_for(@user,:remote => true)  do |f| %>
  <div class="form-group">
    <%= f.label :name ,class:"col-md-1"%>
    <div class="col-md-4">
      <%= f.text_field :name ,placeholder:"Enter Name", class:"form-control"%>
    </div>
  </div>
<br>
<br>


  <div class="form-group">
    <%= f.label :surname ,class:"col-md-1"%>
    <div class="col-md-4">
      <%= f.text_field :surname ,placeholder:"Enter  Surname", class:"form-control"%>
    </div>
  </div>
<br>
<br>

  <div class="form-group">
    <%= f.label :email ,class:"col-md-1"%>
    <div class="col-md-4">
      <%= f.email_field :email ,placeholder:"Enter Email", class:"form-control"%>
    </div>
  </div>
<br>
<br>
  <div class="form-group">
    <%= f.label :mobile,class:"col-md-1"%>
    <div class="col-md-4">
      <%= f.text_field :mobile ,placeholder:"Enter mobile no", class:"form-control"%>
    </div>
  </div>
<br>
<br>
  <div class="form-group">
    <%= f.label :password  ,class:"col-md-1"%>
    <div class="col-md-4">
      <%= f.password_field :password  ,placeholder:"Enter password ", class:"form-control"%>
    </div>
  </div>
<br>
<br>
  <div class="form-group">
    <%= f.label :password_confirmation ,"Confirmation",class:"col-md-1"%>
    <div class="col-md-4">
      <%= f.password_field :password_confirmation ,placeholder:"Enter password ", class:"form-control"%>
    </div>
  </div>
<br>
<br>
  
  <div class="form-group">
    <%= f.submit "Create my account",class:"btn btn-success col-md-4" %>
  </div>
<% end %>
<br>
<br>
<%= link_to 'Back', login_path %>

app/views/users/user_home.html.erb
<div class="row"> 

	<%= button_to "Create New Article", new_user_article_path(params[:id]), method: :get , class:"btn btn-info col-md-4"%>
			
	<%= button_to "View My Articles",  user_articles_user_articles_path(params[:id]) , method: :get , class:"btn btn-success col-md-4"%>
		
	<%= button_to "View Approved Article",articles_list_of_approved_articles_path(), method: :get,class:"btn btn-warning col-md-4" %>
	
</div>