config/routes.rb
Rails.application.routes.draw do
  root   'sessions#new'
 
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
  resources :users  do
    member do
      get 'user_home'
      get 'admin_home'
    end 
    resources :articles do
      collection do
        get 'user_articles'
      end
      member do
        post 'request_status'
        post 'approved_article'
        post 'deny_article'
        get 'show_approved_articles'
        get 'like'
       
      end 
      resources :comments do
        resources :replies
      end   
    end

  end

  namespace :articles do
    get 'list_of_requested_articles'
    get 'list_of_approved_articles'
  end



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
    
    <%if @current_user.present?%>

      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">WebSiteName</a>
          </div>
          <ul class="nav navbar-nav">
            <li class="active">  
              <%if @current_user.user?%>
                <%= link_to 'Home',  user_home_user_path(@current_user) %>
              <%else%>
                <%= link_to 'Home',  admin_home_user_path(@current_user) %>
              <%end%>
            </li>
        
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= button_to 'Logout',logout_path, method: :delete, class:"btn btn-danger btn-lg" %> </li>
            
          </ul>
        </div>
      </nav>
    <% end %>
  </head>

  <body>
    <%= yield %> 
  </body>
</html>